services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    user: "1000:1000"

    ports:
      - "8080:80"

    volumes:
      - /srv:/srv
      - ./database:/database

    command:
      - --root=/srv
      - --database=/database/filebrowser.db

    networks:
      - homeserver

networks:
  homeserver:
    external: true
