services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    labels:
      caddy: homepage.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 3000}}"

    environment:
      PUID: 1000
      PGID: 1000
      HOMEPAGE_ALLOWED_HOSTS: mmserver:3005,homepage.home.arpa:3005,homepage.home.arpa,localhost:3000,127.0.0.1:3000

    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - homeserver

networks:
  homeserver:
    external: true
