services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    pid: host

    environment:
      GLANCES_OPT: "-w"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    networks:
      - homeserver
    labels:
      caddy: glances.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 61208}}"

networks:
  homeserver:
    external: true
