services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data

    networks:
      - homeserver

    labels:
      caddy: portainer.home.arpa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 9000}}"
networks:
  homeserver:
    external: true
