- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://portainer.home.arpa
        description: Docker management

    - Glances:
        icon: glances.png
        href: https://glances.home.arpa
        description: System monitoring

    - File Browser:
        icon: filebrowser.png
        href: https://files.home.arpa
        description: Browse server files

    - AdGuard:
        icon: adguard.png
        href: https://adguard.home.arpa
        description: DNS and ad blocking
        
    - PingvinShare:
        icon: PingvinShare.png
        href: https://share.home.arpa
        description: Sharing is caring
        
    - Docmost:
        icon: Docmost.png
        href: https://docmost.home.arpa
        description: Notion but free and light

    - Website:
        href: https://pietroserver.duckdns.org
        description: Cool public Website

    - Upload Portal:
        icon: mdi-upload
        href: https://upload.home.arpa/admin
        description: Others send files to me
