- Infrastructure:
    - Portainer:
        icon: portainer.png
        href: https://portainer.home.arpa
        description: Docker management

    - Glances:
        icon: glances.png
        href: https://glances.home.arpa
        description: System monitoring

    - File Browser:
        icon: filebrowser.png
        href: https://files.home.arpa
        description: Browse server files

    - AdGuard Home:
        icon: adguard-home.png
        href: https://adguard.home.arpa
        description: DNS and ad blocking

    - Pingvin Share:
        icon: pingvin-share.png
        href: https://share.home.arpa
        description: Sharing is caring

    - Etherpad:
        icon: etherpad.png
        href: https://notes.pietroserver.duckdns.org
        description: Notion but free and light

    - Website:
        icon: firefox.png
        href: https://pietroserver.duckdns.org
        description: Public website

    - Upload Portal:
        icon: mdi-upload
        href: https://upload.home.arpa/admin
        description: Others send files to me
    
    - Crumbs Notes:
        icon: https://crumbs.home.arpa/favicon.ico
        href: https://crumbs.home.arpa
        description: Quick notes









